config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: 'portfolios#index'
  resources :portfolios, only: [:index, :create] do
    collection do
      post :create_contact
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/photo.rb
class Photo
  GALLERY = [
     "https://res.cloudinary.com/dzl2syski/image/upload/v1745854735/AS170_jfj48i.jpg",
    "https://res.cloudinary.com/dzl2syski/image/upload/v1745854735/AS063_lqcp4j.jpg",
    "https://res.cloudinary.com/dzl2syski/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1745855784/53851736629_6f20e85abf_c_l8tym9.jpg",
    "https://res.cloudinary.com/dzl2syski/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1745855814/53986317612_629af82e3d_c_1_balsqe.jpg",
   "https://res.cloudinary.com/dzl2syski/image/upload/v1745854736/AS046_bslpby.jpg",
   "https://res.cloudinary.com/dzl2syski/image/upload/v1745854735/AS090_azftqf.jpg"
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create_contact
    @contact = Contact.new(contacts_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.with(contact: @contact).shout_out.deliver_later
        format.html { redirect_to portfolios_path, notice: "Contact was successfully created." }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("contacts_form", partial: "success_message", locals: { contact: @contact }) }
        format.json { render :index, status: :created  }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("contacts_form", partial: "form", locals: { contact: @contact }) }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def contacts_params
    params.require(:contact).permit("name", "email", "message")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shiladitya | Actor" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
  </head>

  <!-- Purple-Blue Rain Effect -->
<div class="rain" id="rain"></div>

<!-- Navigation Bar -->
<nav>
  <div class="container nav-container">
    <a href="#" class="logo" data-controller="navbar" data-navbar-target="logo">Shiladitya</a>
    <ul class="nav-links">
      <li><a href="#home" class="blue-glow">Home</a></li>
      <li><a href="#resume" class="blue-glow">Resume</a></li>
      <li><a href="#reel" class="blue-glow">Reel</a></li>
      <li><a href="#photos" class="blue-glow">Photos</a></li>
      <li><a href="#contact" class="blue-glow">Contact</a></li>
    </ul>
    <div class="menu-toggle">☰</div>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/portfolios/_about_me.html.erb
<section id="about" class="page-section about-me" data-controller="about-me">
  <div class="container">
    <h2>About Me</h2>
    <div class="resume-content about-me-container" data-about-me-target="container">
      <p>
        Storytelling is my conduit into the prism of consciousness.
      </p>
      <p>
        My being in service to acting.
      </p>
      <p>
        I'm deeply interested in exploring where the spiritual meets the mundane, where the light of hope can burst through the chasm of annihilation, and where the absurd is just a matter of <span data-action="mouseenter->about-me#flicker">perspective</span>.
      </p>
    </div>
  </div>
</section>

app/views/portfolios/_form.html.erb
<section id="contact" class="page-section contact">
    <div class="container">
        <h2>Contact</h2>
        <div class="contact-content">
            <p><strong>Representation</strong></p>
            <p class="coming-soon">Coming Soon</p>
            <%= form_with(model: contact, id: dom_id(contact), url: create_contact_portfolios_path) do |form| %>
              <div>
                <%= form.label :name, "Your Name" %><br>
                <%= form.text_field :name, required: true, class: "contact-input" %>
              </div>

              <div>
                <%= form.label :email, "Your Email" %><br>
                <%= form.email_field :email, required: true, class: "contact-input" %>
              </div>

              <div>
                <%= form.label :message, "Your Message" %><br>
                <%= form.text_area :message, required: true, rows: 6, class: "contact-input" %>
              </div>

              <div class="send-message">
                <%= form.submit "Send Message", class: "hero-btn" %>
              </div>
            <% end %>
        </div>
    </div>
</section>

app/views/portfolios/_photos.html.erb
<section id="photos" class="page-section photos">
  <div class="container">
    <h2>Photographs</h2>
    <div class="gallery" data-controller="gallery">
      <% Photo::GALLERY.each.with_index(1) do |image_url, idx| %>
        <div class="gallery-item" data-action="click->gallery#openModal">
          <%= image_tag image_url, alt: sprintf("Photo_%s", idx) %>
        </div>
      <% end %>

      <div id="photoModal" class="modal" data-gallery-target="modal">
        <span class="modal-close" data-action="click->gallery#closeModal">&times;</span>
        <img id="modalImage" class="modal-content" data-gallery-target="modalImage">
      </div>
    </div>
  </div>
</section>

app/views/portfolios/_resume.html.erb
<section id="resume" class="page-section resume">
  <div class="container">
    <h2>Resume
      <!-- Download Icon next to the header -->
      <%= link_to "https://www.dropbox.com/scl/fi/urxfuvite53hcymzi4qqk/actingResume2025-1.pdf?rlkey=b9vpl2z6ttr8dz377pqpsduz7&st=95aysr8e&dl=1", class: "resume-download-link", target: "_blank", rel: "noopener", download: true do %>
        <svg class="download-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
          <polyline points="7 10 12 15 17 10"></polyline>
          <line x1="12" y1="15" x2="12" y2="3"></line>
        </svg>
      <% end %>
    </h2>
    <div class="resume-content">
      <h3>Film/Television</h3>
      <div class="resume-items">
        <div class="resume-item">
          <div class="project-title"><strong>Half Half</strong> (short)</div>
          <div class="role-details">Taher <span class="role-type">(lead)</span> - dir. Danny Chen</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Homies</strong> (short)</div>
          <div class="role-details">Vape <span class="role-type">(lead)</span> - dir. El Josar & Shiladitya</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Native</strong> (short)</div>
          <div class="role-details">Man <span class="role-type">(lead)</span> - dir. Farah Albani</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Generation Scam (HBO/Vice)</strong></div>
          <div class="role-details">Syed Arbab <span class="role-type">(lead)</span> dir: George Plamondon</div>
        </div>
      </div>

      <h3>Theater</h3>
      <div class="resume-items">
        <div class="resume-item">
          <div class="project-title"><strong>Master and the Margharita</strong></div>
          <div class="role-details">The Master / Yeshua - Royal Conservatoire of Scotland/ dir. Liz Birrenbach</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Antigone</strong></div>
          <div class="role-details">Guard/Chorus - Royal Conservatoire of Scotland/ dir. Leonor Estrada</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Richard II</strong></div>
          <div class="role-details">Richard II / John of Gaunt - Globe Theater Residency/ dir. Michael Brown</div>
        </div>
      </div>

      <h3>Training</h3>
      <div class="resume-items">
        <div class="resume-item">
          <div class="project-title"><strong><%= link_to "Royal Conservatoire of Scotland", "https://www.rcs.ac.uk/bio/aditya-singh/", class: "rcs-link" %></strong></div>
          <div class="role-details">Master of Arts: Classical and Contemporary Text</div>
        </div>
        <div class="resume-item">
          <div class="project-title"><strong>Ecole Philip Gaulier School</strong></div>
          <div class="role-details">Le Jeu, Neutral Mask, Greek Tragedy</div>
        </div>
      </div>

      <h3>Skills</h3>
      <div class="resume-items skills-section">
        <div class="skill-tag">Movement (Laban, Grotowski, Viewpoints)</div>
        <div class="skill-tag">Dancing (Samba)</div>
        <div class="skill-tag">Singing (Baritone)</div>
        <div class="skill-tag">Languages (Hindi - fluent, Spanish - conversational)</div>
        <div class="skill-tag">Accents (Indian, General American, East Coast, Southern)</div>
        <div class="skill-tag">Combat (Muay Thai Kickboxing)</div>
      </div>
    </div>
  </div>
</section>

app/views/portfolios/_success_message.html.erb
<div class="contact-success-message">
  <div class="contact-success-line">
    <h2>Thank you, <%= @contact.name.capitalize %>!</h2>
  </div>
  
  <div class="contact-success-line">
    <p>Message received! I shall get back to you soon ;)</p>
  </div>
</div>

app/views/portfolios/index.html.erb
<%= turbo_stream_from "contacts" %>

<!-- Hero Section -->
<section id="home" class="hero">
  <div class="container hero-content">
    <h1>Shiladitya</h1>
    <p>Actor • Performer • Writer</p>
    <a href="#contact" class="hero-btn">Cross the Void</a>
  </div>
</section>

<div class="neon-divider"></div>

<!-- About Me Section -->
<%= render "about_me"  %>
<div class="neon-divider"></div>

<!-- Resume Section -->
<%= render "resume"  %>

<div class="neon-divider"></div>

<!-- Reel Section -->
<section id="reel" class="page-section reel">
  <div class="container">
    <h2>Demo Reel</h2>
    <div class="video-container">
      <div class="video-placeholder">
      <iframe width="100%" height="500"
        src="https://www.youtube.com/embed/TAd7n9uHfHo?si=6ZN5jio3f5hSpXvO"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
      </div>
    </div>
  </div>
</section>

<div class="neon-divider"></div>

<!-- Photos Section -->
<%= render "photos"  %>

<div class="neon-divider"></div>

<!-- Contact Section -->
<%= turbo_frame_tag "contacts_form" do %>
  <%= render "portfolios/form", contact: @contact %>
<% end %>